version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - errname
    - errorlint
    - gocritic
    - ineffassign
    - misspell
    - nolintlint
    - unused
  settings:
    errorlint:
      asserts: false
      comparison: false
    gocritic:
      disabled-checks:
        - ifElseChain
        - dupSubExpr
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: non-wrapping format verb for fmt.Errorf
    paths:
      - playground
      - docs
      - scripts
      - stapel
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/deckhouse/delivery-kit-sdk)
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - playground
      - docs
      - scripts
      - stapel
      - third_party$
      - builtin$
      - examples$
