name: Test E2E Longterm

on: [push]

jobs:
  test-longterm:
    runs-on: ubuntu-22.04

    timeout-minutes: 30

    permissions:
      contents: read
      id-token: write

    env:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_ROLE: ${{ secrets.VAULT_ROLE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Install project dependencies
        run: task deps:install

      - name: Test E2E Longterm
        run: task test:e2e labelFilter=longterm
